package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

/**
 * UserInfo generated by hbm2java
 */
public class OldUserCard implements java.io.Serializable {
	private Integer id;
	private String userName;
	private String realName;
	private String bankAcc;
	
	public OldUserCard() {
	}

	public OldUserCard(String userName,String bankAcc,String realName) {
		this.userName = userName;
		this.bankAcc = bankAcc;
		this.realName = realName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getBankAcc() {
		return bankAcc;
	}

	public void setBankAcc(String bankAcc) {
		this.bankAcc = bankAcc;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	
}
