package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * LotteryPlReport generated by hbm2java
 */
public class StatBettingNumber implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8088273107305984393L;
	
	private Integer id;
	private String lotteryType;
	private Integer issueId;
	private String issueNum;
	private Integer playTypeId;
	private String playTypeName;
	private String betNum;
	private BigDecimal betAmount;
	private Date createTime;

	public StatBettingNumber() {
	}

	public StatBettingNumber(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLotteryType() {
		return lotteryType;
	}

	public void setLotteryType(String lotteryType) {
		this.lotteryType = lotteryType;
	}

	public Integer getIssueId() {
		return issueId;
	}

	public void setIssueId(Integer issueId) {
		this.issueId = issueId;
	}

	public String getIssueNum() {
		return issueNum;
	}

	public void setIssueNum(String issueNum) {
		this.issueNum = issueNum;
	}

	public Integer getPlayTypeId() {
		return playTypeId;
	}

	public void setPlayTypeId(Integer playTypeId) {
		this.playTypeId = playTypeId;
	}

	public String getPlayTypeName() {
		return playTypeName;
	}

	public void setPlayTypeName(String playTypeName) {
		this.playTypeName = playTypeName;
	}

	public String getBetNum() {
		return betNum;
	}

	public void setBetNum(String betNum) {
		this.betNum = betNum;
	}

	public BigDecimal getBetAmount() {
		return betAmount;
	}

	public void setBetAmount(BigDecimal betAmount) {
		this.betAmount = betAmount;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	
}
