package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * WithdrawApplication generated by hbm2java
 */
public class TransferApplication implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 397203253822245644L;
	private Integer id;
	private String orderNum;
	private Integer sourceUser;
	private String sourceUserName;
	private Integer sourceWalletId;
	private String sourceWalletName;
	private Integer dstUser;
	private String dstUserName;
	private Integer dstWalletId;
	private String dstWalletName;
	private Double amount;
	private Integer state;
	private Date createTime;
	private Date updateTime;
	private Integer creator;

	public TransferApplication() {
	}

	public TransferApplication(String orderNum, Integer sourceUser, Integer sourceWalletId, Integer dstUser, Integer dstWalletId, Double amount,
			Integer state, Date createTime, Date updateTime, Integer creator) {
		this.orderNum = orderNum;
		this.sourceUser = sourceUser;
		this.sourceWalletId = sourceWalletId;
		this.dstUser = dstUser;
		this.dstWalletId = dstWalletId;
		this.amount = amount;
		this.state = state;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.creator = creator;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getSourceUser() {
		return sourceUser;
	}

	public void setSourceUser(Integer sourceUser) {
		this.sourceUser = sourceUser;
	}

	public Integer getSourceWalletId() {
		return sourceWalletId;
	}

	public void setSourceWalletId(Integer sourceWalletId) {
		this.sourceWalletId = sourceWalletId;
	}

	public Integer getDstUser() {
		return dstUser;
	}

	public void setDstUser(Integer dstUser) {
		this.dstUser = dstUser;
	}

	public Integer getDstWalletId() {
		return dstWalletId;
	}

	public void setDstWalletId(Integer dstWalletId) {
		this.dstWalletId = dstWalletId;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public String getSourceUserName() {
		return sourceUserName;
	}

	public void setSourceUserName(String sourceUserName) {
		this.sourceUserName = sourceUserName;
	}

	public String getSourceWalletName() {
		return sourceWalletName;
	}

	public void setSourceWalletName(String sourceWalletName) {
		this.sourceWalletName = sourceWalletName;
	}

	public String getDstUserName() {
		return dstUserName;
	}

	public void setDstUserName(String dstUserName) {
		this.dstUserName = dstUserName;
	}

	public String getDstWalletName() {
		return dstWalletName;
	}

	public void setDstWalletName(String dstWalletName) {
		this.dstWalletName = dstWalletName;
	}
	
	
}
