package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * SysCode generated by hbm2java
 */
public class UserInfoExt implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String extFieldName;
	private String extFieldVal;
	private Date createTime;

	public UserInfoExt() {
	}

	public UserInfoExt(Integer id, Integer userId,  String extFieldName, String extFieldVal, Date createTime) {
		this.id = id;
		this.userId = userId;
		this.extFieldName = extFieldName;
		this.extFieldVal = extFieldVal;
		this.createTime = createTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getExtFieldName() {
		return extFieldName;
	}

	public void setExtFieldName(String extFieldName) {
		this.extFieldName = extFieldName;
	}

	public String getExtFieldVal() {
		return extFieldVal;
	}

	public void setExtFieldVal(String extFieldVal) {
		this.extFieldVal = extFieldVal;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	
	
}
