package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * SysRole generated by hbm2java
 */
public class UserSettlement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8508713772551044308L;
	private Integer id;
	private Integer userId;
	private String userName;
	private Integer state;
	private Double creditLimit;
	private Double availableCredit;
	private Date setDate;
	private Date createTime;

	public UserSettlement() {
	}

	public UserSettlement(Integer userId, String userName, Integer state, Double creditLimit, Double availableCredit, Date setDate, Date createTime) {
		this.userId = userId;
		this.userName = userName;
		this.state = state;
		this.creditLimit = creditLimit;
		this.availableCredit = availableCredit;
		this.setDate = setDate;
		this.createTime = createTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	

	public Double getCreditLimit() {
		return creditLimit;
	}

	public void setCreditLimit(Double creditLimit) {
		this.creditLimit = creditLimit;
	}

	public Double getAvailableCredit() {
		return availableCredit;
	}

	public void setAvailableCredit(Double availableCredit) {
		this.availableCredit = availableCredit;
	}

	public Date getSetDate() {
		return setDate;
	}

	public void setSetDate(Date setDate) {
		this.setDate = setDate;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	
}
