package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Issue generated by hbm2java
 */
public class UserPushConfig implements java.io.Serializable {
		
	/**
	 * 
	 */
	private static final long serialVersionUID = -4065414277850584225L;
	
	private Integer id;
	private String lotteryType;
	private Integer userId;
	private Integer playTypeId;
	private String playTypeName;
	
	private Integer pushTimes;
	private Double pushAmount;
	private Integer pushNumbers;
	private Integer state;
	private Date createTime;
	

	public UserPushConfig() {
	}

	public UserPushConfig(String lotteryType, Integer userId, Integer playTypeId, 
			String playTypeName, 
			Integer pushTimes, Double pushAmount, Integer pushNumbers,
			Date createTime) {
		this.lotteryType = lotteryType;
		this.userId = userId;
		this.playTypeId = playTypeId;
		this.playTypeName = playTypeName;
		this.pushTimes = pushTimes;
		this.pushAmount = pushAmount;
		this.pushNumbers = pushNumbers;
		this.createTime = createTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLotteryType() {
		return lotteryType;
	}

	public void setLotteryType(String lotteryType) {
		this.lotteryType = lotteryType;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getPlayTypeId() {
		return playTypeId;
	}

	public void setPlayTypeId(Integer playTypeId) {
		this.playTypeId = playTypeId;
	}

	public String getPlayTypeName() {
		return playTypeName;
	}

	public void setPlayTypeName(String playTypeName) {
		this.playTypeName = playTypeName;
	}

	public Integer getPushTimes() {
		return pushTimes;
	}

	public void setPushTimes(Integer pushTimes) {
		this.pushTimes = pushTimes;
	}

	public Double getPushAmount() {
		return pushAmount;
	}

	public void setPushAmount(Double pushAmount) {
		this.pushAmount = pushAmount;
	}

	public Integer getPushNumbers() {
		return pushNumbers;
	}

	public void setPushNumbers(Integer pushNumbers) {
		this.pushNumbers = pushNumbers;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
}
