package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

/**
 * UserInfo generated by hbm2java
 */
public class UserRebate implements java.io.Serializable {
	private Integer id;
	private String userName;
	private Double rebate;
	
	public UserRebate() {
	}

	public UserRebate(String userName,Double rebate) {
		this.userName = userName;
		this.rebate = rebate;
	}

	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Double getRebate() {
		return rebate;
	}

	public void setRebate(Double rebate) {
		this.rebate = rebate;
	}
}
